### ISSUE TITLE
Installeren nodige tools

### ISSUE THREAD

**Issue by Villadelfia** [PXL-Embedded-AI/repo#19]
Verplicht:
- Qt Creator: [Download hier](https://www.qt.io/download-qt-installer)
  - [Settings 1](https://i.imgur.com/GMjBSQT.png)
  - [Settings 2](https://i.imgur.com/GV1wQAs.png)
- VS Code: [Download hier](https://code.visualstudio.com/)
- PlatformIO: [Download hier](https://platformio.org/install/ide?install=vscode)
- OpenMV IDE: [Download hier](https://openmv.io/pages/download)

Optioneel:
 - Gitkraken: [Download hier](https://www.gitkraken.com/)

**Reagier hier als deze taak compleet is!**

**Comment by i5cP7i** [comment]
Alles geïnstalleerd incl. Gitkraken

**Comment by Villadelfia** [comment]
Alles geinstalleerd.

**Comment by maudceyssens** [comment]
done

**Comment by kiks3107** [comment]
alles is al geinstalleerd was vergeten het hier te zetten
