### ISSUE TITLE
Meer tools installeren

### ISSUE THREAD

**Issue by Villadelfia** [PXL-Embedded-AI/repo#21]
Het is ook belangrijk dat jullie Visual Studio 2019 installeren met de C/C++ modules [te downloaden hier](https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=Community&rel=16)

Specifiek bedoel ik hiermee de "C++ for desktop" optie in de installer.

**Comment by Villadelfia** [comment]
gedaan

**Comment by maudceyssens** [comment]
klaar

**Comment by i5cP7i** [comment]
done.

**Comment by kiks3107** [comment]
complete
