### ISSUE TITLE
bestellingslijst doorsturen:

### ISSUE THREAD

**Issue by Villadelfia** [PXL-Embedded-AI/repo#25]
- link
 - productcode
 - prijs
 - aantal
 - bij 3 leveranciers

Doorsturen ten laatste 12 maart ochtend.

**Comment by i5cP7i** [comment]
De (low-cost) diffraction grating cards zijn te verkrijgen bij Amazon via Rainbow symphony. De "Vincent leermiddelen Scientific" [leermiddelen.be](http://www.leermiddelen.be/nl/dias-en-filters) biedt een hogere kwaliteit aan voor een hogere prijs, en meerdere relevante artikelen (zoals diafragma's, filters, halogeenlampen, etc.). 

Bijgevoegd de (voorlopige) bestellingslijst:

[onderdelen-EmbeddedAI-v1_00.docx](https://github.com/PXL-Embedded-AI/repo/files/4321467/onderdelen-EmbeddedAI-v1_00.docx)
[onderdelen-EmbeddedAI-v1_00.pdf](https://github.com/PXL-Embedded-AI/repo/files/4321468/onderdelen-EmbeddedAI-v1_00.pdf)

Edit: bijgevoegde bestanden kwamen niet overeen

**Comment by i5cP7i** [comment]
Update:
[onderdelen-EmbeddedAI-v1_01.pdf](https://github.com/PXL-Embedded-AI/repo/files/4321548/onderdelen-EmbeddedAI-v1_01.pdf)
[onderdelen-EmbeddedAI-v1_01.docx](https://github.com/PXL-Embedded-AI/repo/files/4321549/onderdelen-EmbeddedAI-v1_01.docx)

**Comment by Villadelfia** [comment]
Doorsturen naar Koen. Bart & Vincent in CC.

**Comment by Villadelfia** [comment]
Daarna closen en in done zetten.

**Comment by i5cP7i** [comment]
Bestellingslijst is verzonden naar Koen Gilissen:

![Bestellingslijst-EmbeddedAI-bewijs](https://user-images.githubusercontent.com/48355782/76952432-60569600-690d-11ea-801f-1d4e2833feab.png)
